### PR TITLE
Game branch

### PR DESCRIPTION
**Pull request by annagaiel**
Hi, I run the game migration to only have the white_player_id   , black_player_id field rather than name field.

### CODE REVIEW

**Comment by ghost** [comment]
Hey Anna, 

I think you forgot a few things. 
Games model - has_many : Pieces
User model - has_many :Pieces

are you waiting to include the Pieces later?

Also for the Games model, you put 

belongs_to: User

I think it should be

has_many: user 

belongs_to will make the Game the "child" and I think Game should be the "parent"

Yes, no?

**Comment by annagaiel** [comment]
Hi David,

Can you review the user_piece_branch. I placed modifications there. You can do a remote commit on that branch if you see me miss any important association.  

I noticed that in the nomster and flixter we had the course and place belong to the user since user has many places and courses. I think its the same in this chess game. The user can have many games. User can create a new game and that the game is associated to the user.

That is why I changed it.

**Comment by ghost** [comment]
Oh ok that makes sense. Ha I forgot about using Nomster and Flixter as
guides. Good idea.

I'm checking out the user_piece_branch now.

**Comment by ghost** [comment]
Oh wait, I have a question. Github is saying this branch has conflicts that must be resolved. It's because we didn't do rake db:migrate.  Once I ran rake db:migrate, everything appeared fine on my local host.

Should we do this first and then merge to master?

**Comment by ghost** [comment]
oh you naughty naughty girl x2
Now you have to buy us a round of drinks! :)

**Pull request merged**
