### PR TITLE
User piece branch

### PR DESCRIPTION
**Pull request by ghost**
Ok, this branch is cleaned up and rake db:migrate has been run. I added t.integer : game_id since it was left off.

### CODE REVIEW

**Comment by dvanetten03** [comment]
I can't review this branch until mine has been approved and merged.  Once that happens I can review this.

**Comment by annagaiel** [comment]
Do not merge this, the id is not associated correctly and I am merging the current master to a new branch id_table.

**Comment by dvanetten03** [comment]
What do you mean you are merging the current master to a new branch?  I'm a little concerned, Anna, that you have merged a number of things to master without working with the rest of the group and we don't all seem to be on the same page.  It's going to be important that we all understand what is going on...why is the id not associated correctly?

**Comment by annagaiel** [comment]
Hi @dvanetten03 and @davidslee101 ,

The added ids are not needed. It does not make sense to add that when rails does not for us.
When we created course db did you explicitly wrote course_id. I think its in flixter 12.

You can review these files:
db/migrate/20150923200320_create_games.rb
- t.integer :game_id

# 

db/migrate/20150924180824_create_pieces.rb
- t.integer :piece_id

**Comment by annagaiel** [comment]
@dvanetten03  - The new branch is id_table where the piece has the associated id of game and user.

About the merging, I thought we agreed that if two people has the branch working we can branch.

I saw you approve the nav_bar branch and I saw mentor aaron approve your develop branch and because those branches are also working on mine. I merged them. If you want the branch to be working on at least three people, let me know. I'm glad that codeship broke in this early stage. @kirubel  and @davidslee101 can work on that original task. I also find the reverting vs creating new branches to be a great lesson for us the team.

**Comment by ghost** [comment]
Hey Anna, you are correct for merging. We should stick to 2 people giving
it a thumbs up. However they need to be 2 people who are not the person who
originally created the branch. So the issue was that you are merging
branches that you created but you are counting yourself as one of the 2
people.

Also, we should always run rake db:migrate on our branch before merging it
into the master, that is why I reverted the commits yesterday, and that is
why Diane's merge is not working (she made her branch from a the master
that had the commits I reverted). I put a slack channel message not to
merge Diane's PR until the user_piece_branch PR I made yesterday was
merged. Once we merge my PR on user_piece_branch, we should be fine.

Anna, I do see your point with game_id and piece_id, but Aaron, can you
confirm that we do not need

 t.integer :game_id in our game database and
 t.integer :piece_id in our piece.rb in our pieces database?

I think I'm confused because we had it on our database spreadsheet and it's
something I know we need.

David Lee

**Pull request closed without merging**
